### ISSUE TITLE
Retraction value accept only integer

### ISSUE THREAD

**Issue by FedorZa** [ArtificalSUN/Kcalibrator#5]

**Comment by FedorZa** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "kcalibrator.pyw", line 582, in update_and_create
    currentConfig.updatesettings(top)
  File "kcalibrator.pyw", line 71, in updatesettings
    self.retract = (int(root.retract_length_entry.get()), int(root.retract_speed_entry.get()))
ValueError: invalid literal for int() with base 10: '0.5'
started creategcode
stopped creategcode
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "kcalibrator.pyw", line 582, in update_and_create
    currentConfig.updatesettings(top)
  File "kcalibrator.pyw", line 71, in updatesettings
    self.retract = (int(root.retract_length_entry.get()), int(root.retract_speed_entry.get()))
ValueError: invalid literal for int() with base 10: '0.5'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "kcalibrator.pyw", line 582, in update_and_create
    currentConfig.updatesettings(top)
  File "kcalibrator.pyw", line 71, in updatesettings
    self.retract = (int(root.retract_length_entry.get()), int(root.retract_speed_entry.get()))
ValueError: invalid literal for int() with base 10: '0.5'

**Comment by ArtificalSUN** [comment]
You are using an old version, please use the latest one
